import type { Metadata } from "next";
import { Space_Mono, Barlow } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Load the Gliker font from the local 'gliker' folder
const gliker = localFont({
  src: [
    {
      path: "../gliker/Gliker-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../gliker/Gliker-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    // Add more weights/styles if you have them
  ],
  variable: "--font-gliker",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${spaceMono.variable} ${barlow.variable} ${gliker.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
