name: Update README with Screenshots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Start the website
        run: npm run start &
        env:
          PORT: 3000

      - name: Wait for website to be ready
        run: |
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 2; done' || false

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Take screenshots
        run: |
          npx playwright screenshot http://localhost:3000 ./public/desktop.png --viewport-size=1920,1080
          npx playwright screenshot http://localhost:3000 ./public/mobile.png --viewport-size=375,812

      - name: Update README with new screenshots
        run: |
          sed -i 's|https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&auto=format&fit=crop&q=60|https://raw.githubusercontent.com/jehanzaib084/aura-bora/main/public/desktop.png|g' README.md
          sed -i 's|https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&auto=format&fit=crop&q=60|https://raw.githubusercontent.com/jehanzaib084/aura-bora/main/public/mobile.png|g' README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md public/desktop.png public/mobile.png
          git commit -m "Update README with new screenshots" || exit 0
          git push 